// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	category "github.com/leyl1ne/ProductService/internal/model/category"

	mock "github.com/stretchr/testify/mock"

	product "github.com/leyl1ne/ProductService/internal/model/product"

	serviceproduct "github.com/leyl1ne/ProductService/internal/service/product"

	uuid "github.com/google/uuid"
)

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

// CreateProduct provides a mock function with given fields: ctx, _a1
func (_m *Repository) CreateProduct(ctx context.Context, _a1 product.Product) (*product.Product, error) {
	ret := _m.Called(ctx, _a1)

	if len(ret) == 0 {
		panic("no return value specified for CreateProduct")
	}

	var r0 *product.Product
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, product.Product) (*product.Product, error)); ok {
		return rf(ctx, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, product.Product) *product.Product); ok {
		r0 = rf(ctx, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*product.Product)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, product.Product) error); ok {
		r1 = rf(ctx, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteProduct provides a mock function with given fields: ctx, id
func (_m *Repository) DeleteProduct(ctx context.Context, id uuid.UUID) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteProduct")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetCategoryByID provides a mock function with given fields: ctx, id
func (_m *Repository) GetCategoryByID(ctx context.Context, id uuid.UUID) (*category.Category, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetCategoryByID")
	}

	var r0 *category.Category
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*category.Category, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *category.Category); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*category.Category)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetProductAvailability provides a mock function with given fields: ctx, productID
func (_m *Repository) GetProductAvailability(ctx context.Context, productID uuid.UUID) ([]serviceproduct.AvailableBatch, error) {
	ret := _m.Called(ctx, productID)

	if len(ret) == 0 {
		panic("no return value specified for GetProductAvailability")
	}

	var r0 []serviceproduct.AvailableBatch
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]serviceproduct.AvailableBatch, error)); ok {
		return rf(ctx, productID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []serviceproduct.AvailableBatch); ok {
		r0 = rf(ctx, productID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]serviceproduct.AvailableBatch)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, productID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetProductByID provides a mock function with given fields: ctx, id
func (_m *Repository) GetProductByID(ctx context.Context, id uuid.UUID) (*product.Product, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetProductByID")
	}

	var r0 *product.Product
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*product.Product, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *product.Product); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*product.Product)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListCategories provides a mock function with given fields: ctx
func (_m *Repository) ListCategories(ctx context.Context) ([]category.Category, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListCategories")
	}

	var r0 []category.Category
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]category.Category, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []category.Category); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]category.Category)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListProducts provides a mock function with given fields: ctx, filter, page, limit
func (_m *Repository) ListProducts(ctx context.Context, filter serviceproduct.ProductFilter, page int, limit int) (*serviceproduct.ProductListResult, error) {
	ret := _m.Called(ctx, filter, page, limit)

	if len(ret) == 0 {
		panic("no return value specified for ListProducts")
	}

	var r0 *serviceproduct.ProductListResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, serviceproduct.ProductFilter, int, int) (*serviceproduct.ProductListResult, error)); ok {
		return rf(ctx, filter, page, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, serviceproduct.ProductFilter, int, int) *serviceproduct.ProductListResult); ok {
		r0 = rf(ctx, filter, page, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*serviceproduct.ProductListResult)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, serviceproduct.ProductFilter, int, int) error); ok {
		r1 = rf(ctx, filter, page, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateProduct provides a mock function with given fields: ctx, id, params
func (_m *Repository) UpdateProduct(ctx context.Context, id uuid.UUID, params serviceproduct.UpdateProductParams) (*product.Product, error) {
	ret := _m.Called(ctx, id, params)

	if len(ret) == 0 {
		panic("no return value specified for UpdateProduct")
	}

	var r0 *product.Product
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, serviceproduct.UpdateProductParams) (*product.Product, error)); ok {
		return rf(ctx, id, params)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, serviceproduct.UpdateProductParams) *product.Product); ok {
		r0 = rf(ctx, id, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*product.Product)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, serviceproduct.UpdateProductParams) error); ok {
		r1 = rf(ctx, id, params)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewRepository creates a new instance of Repository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *Repository {
	mock := &Repository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
