// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	batch "github.com/leyl1ne/ProductService/internal/model/batch"

	mock "github.com/stretchr/testify/mock"

	product "github.com/leyl1ne/ProductService/internal/model/product"

	servicebatch "github.com/leyl1ne/ProductService/internal/service/batch"

	uuid "github.com/google/uuid"
)

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

// CreateBatch provides a mock function with given fields: ctx, _a1
func (_m *Repository) CreateBatch(ctx context.Context, _a1 batch.ProductBatch) (*batch.ProductBatch, error) {
	ret := _m.Called(ctx, _a1)

	if len(ret) == 0 {
		panic("no return value specified for CreateBatch")
	}

	var r0 *batch.ProductBatch
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, batch.ProductBatch) (*batch.ProductBatch, error)); ok {
		return rf(ctx, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, batch.ProductBatch) *batch.ProductBatch); ok {
		r0 = rf(ctx, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*batch.ProductBatch)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, batch.ProductBatch) error); ok {
		r1 = rf(ctx, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteBatch provides a mock function with given fields: ctx, id
func (_m *Repository) DeleteBatch(ctx context.Context, id uuid.UUID) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteBatch")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetBatchByID provides a mock function with given fields: ctx, id
func (_m *Repository) GetBatchByID(ctx context.Context, id uuid.UUID) (*batch.ProductBatch, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetBatchByID")
	}

	var r0 *batch.ProductBatch
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*batch.ProductBatch, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *batch.ProductBatch); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*batch.ProductBatch)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetProductByID provides a mock function with given fields: ctx, id
func (_m *Repository) GetProductByID(ctx context.Context, id uuid.UUID) (*product.Product, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetProductByID")
	}

	var r0 *product.Product
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*product.Product, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *product.Product); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*product.Product)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListBatchesByProduct provides a mock function with given fields: ctx, productID
func (_m *Repository) ListBatchesByProduct(ctx context.Context, productID uuid.UUID) ([]batch.ProductBatch, error) {
	ret := _m.Called(ctx, productID)

	if len(ret) == 0 {
		panic("no return value specified for ListBatchesByProduct")
	}

	var r0 []batch.ProductBatch
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]batch.ProductBatch, error)); ok {
		return rf(ctx, productID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []batch.ProductBatch); ok {
		r0 = rf(ctx, productID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]batch.ProductBatch)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, productID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateBatch provides a mock function with given fields: ctx, id, params
func (_m *Repository) UpdateBatch(ctx context.Context, id uuid.UUID, params servicebatch.UpdateBatchParams) (*batch.ProductBatch, error) {
	ret := _m.Called(ctx, id, params)

	if len(ret) == 0 {
		panic("no return value specified for UpdateBatch")
	}

	var r0 *batch.ProductBatch
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, servicebatch.UpdateBatchParams) (*batch.ProductBatch, error)); ok {
		return rf(ctx, id, params)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, servicebatch.UpdateBatchParams) *batch.ProductBatch); ok {
		r0 = rf(ctx, id, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*batch.ProductBatch)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, servicebatch.UpdateBatchParams) error); ok {
		r1 = rf(ctx, id, params)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewRepository creates a new instance of Repository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *Repository {
	mock := &Repository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
